export const flightCopy = {
  title: "Career Flight",
  hangarTitle: "Hangar",
  hangarBody: "Pick a sky and a craft, then explore the career district.",
  launch: "Launch",
  land: "Land",
  cancel: "Cancel",
  respawn: "Respawn",
  returnPlatform: "Return to platform",
  deepSpaceTitle: "Deep space",
  deepSpaceBody:
    "You’ve left the staging island. The galaxy stretches for hundreds of units — chase distant worlds, or return whenever you like.",
  skyLabel: "Sky",
  craftLabel: "Craft",
  ctaHero: "Take Career Flight",
  ctaExperience: "Explore the district",
  footerAria: "Take a flight through my career district",
  desktopOnly:
    "This easter egg is built for keyboard - try it on desktop.",
  reducedMotionTitle: "Career district",
  contact: "Contact",
  resume: "Resume",
  openLink: "Open link",
  controlsHint: "WASD / arrows · Shift boost · R respawn · Esc cancel",
  discoveredLabel: "Found",
  coinsLabel: "Coins",
  progress: (found: number, total: number) => `${found}/${total}`,
} as const;
